### ISSUE TITLE
Please test your *.exe with virustotal

### ISSUE THREAD

**Issue by onetoomanyonesandzeroes** [krmax44/UnsplashWallpapers#1]
What do you think?
https://www.virustotal.com/gui/file/c1bf9659c9a6e3a3d944f4a1a938f254b22bf8b419f5a326a335577ebcd1f705/detection

**Comment by krmax44** [comment]
This is a known flaw with the tool I used to create the exe file from the bat files. If you don't trust the binaries, you can either compile them yourself easily thanks to the intuitive GUI of Bat2Exe, see the [wiki](https://github.com/krmax44/UnsplashWallpapers/wiki/Recompile-the-bat-file) or simply use the source bat file.
